steps:
- name: gcr.io/$PROJECT_ID/build-container:0.2
  args: ['./build.sh']
  env: ['glibc_install=/workspace/build/install']
- name: gcr.io/$PROJECT_ID/build-container:0.2
  args: ['tar -czf install.tar.gz -C /workspace/build/install .']
artifacts:
  objects:
    location: 'gs://glibc-cloudbuild'
    paths: ['install.tar.gz']
timeout: 1800s
