steps:
- name: build-container:0.2
  args: ['./build.sh']
  env: ['glibc_install=/workspace/build/install']
- name: build-container:0.1
  args: ['tar -czf install.tar.gz -C /workspace/build/install .']
artifacts:
  objects:
    location: 'gs://glibc-cloudbuild'
    paths: ['install.tar.gz']

